-- ============================================================
-- Post-deploy cron: drain the inbox buffer every minute (pg_cron + pg_net)
--
-- WHY this is not a migration: the job needs your live prod URL and CRON_SECRET,
-- which only exist AFTER the first Vercel deploy. The extensions it relies on are
-- enabled by migration 20260615000003_enable_pg_cron_pg_net (applied via db push).
--
-- HOW to run: replace the two placeholders with the values from your .env.local,
-- then run this in the Supabase dashboard -> SQL Editor. (scripts/setup.mjs can
-- fill it for you and print the ready-to-paste SQL.) It is idempotent: re-running
-- updates the existing 'buffer-flush' job in place.
--
--   __APP_URL__      -> NEXT_PUBLIC_APP_URL  (e.g. https://your-app.vercel.app -- NO trailing slash)
--   __CRON_SECRET__  -> CRON_SECRET          (hex secret generated by scripts/setup.mjs)
-- ============================================================

select cron.schedule(
  'buffer-flush',          -- unique job name; re-scheduling updates it in place
  '* * * * *',             -- every minute
  $job$
    select net.http_get(
      url     := '__APP_URL__/api/cron/buffer-flush',
      headers := jsonb_build_object('Authorization', 'Bearer __CRON_SECRET__')
    );
  $job$
);

-- Commerce: retry AFIP invoicing for paid orders without a CAE (hourly).
select cron.schedule(
  'invoice-retry',
  '15 * * * *',            -- every hour at :15
  $job$
    select net.http_get(
      url     := '__APP_URL__/api/cron/invoice-retry',
      headers := jsonb_build_object('Authorization', 'Bearer __CRON_SECRET__')
    );
  $job$
);

-- Commerce: decay inactive customers to 'inactive' tier (daily 03:00 UTC = 00:00 ART).
select cron.schedule(
  'tier-decay',
  '0 3 * * *',             -- daily at 03:00 UTC
  $job$
    select net.http_get(
      url     := '__APP_URL__/api/cron/tier-decay',
      headers := jsonb_build_object('Authorization', 'Bearer __CRON_SECRET__')
    );
  $job$
);

-- Verify they registered (expect three active rows):
--   select jobname, schedule, active from cron.job
--   where jobname in ('buffer-flush', 'invoice-retry', 'tier-decay');
--
-- Inspect recent runs / failures:
--   select status, return_message, start_time
--   from cron.job_run_details
--   where jobid = (select jobid from cron.job where jobname = 'buffer-flush')
--   order by start_time desc limit 10;
--
-- Remove the job:
--   select cron.unschedule('buffer-flush');
