-- ============================================================
-- Post-deploy cron: drain the inbox buffer every minute (pg_cron + pg_net)
--
-- WHY this is not a migration: the job needs your live prod URL and CRON_SECRET,
-- which only exist AFTER the first Vercel deploy. The extensions it relies on are
-- enabled by migration 20260615000003_enable_pg_cron_pg_net (applied via db push).
--
-- HOW to run: replace the two placeholders with the values from your .env.local,
-- then run this in the Supabase dashboard -> SQL Editor. (scripts/setup.mjs can
-- fill it for you and print the ready-to-paste SQL.) It is idempotent: re-running
-- updates the existing 'buffer-flush' job in place.
--
--   __APP_URL__      -> NEXT_PUBLIC_APP_URL  (e.g. https://your-app.vercel.app -- NO trailing slash)
--   __CRON_SECRET__  -> CRON_SECRET          (hex secret generated by scripts/setup.mjs)
-- ============================================================

select cron.schedule(
  'buffer-flush',          -- unique job name; re-scheduling updates it in place
  '* * * * *',             -- every minute
  $job$
    select net.http_get(
      url     := '__APP_URL__/api/cron/buffer-flush',
      headers := jsonb_build_object('Authorization', 'Bearer __CRON_SECRET__')
    );
  $job$
);

-- Commerce: retry AFIP invoicing for paid orders without a CAE (hourly).
select cron.schedule(
  'invoice-retry',
  '15 * * * *',            -- every hour at :15
  $job$
    select net.http_get(
      url     := '__APP_URL__/api/cron/invoice-retry',
      headers := jsonb_build_object('Authorization', 'Bearer __CRON_SECRET__')
    );
  $job$
);

-- Commerce: decay inactive customers to 'inactive' tier (daily 03:00 UTC = 00:00 ART).
select cron.schedule(
  'tier-decay',
  '0 3 * * *',             -- daily at 03:00 UTC
  $job$
    select net.http_get(
      url     := '__APP_URL__/api/cron/tier-decay',
      headers := jsonb_build_object('Authorization', 'Bearer __CRON_SECRET__')
    );
  $job$
);

-- Commerce: recordatorio de carritos abandonados (cada hora a los :30).
select cron.schedule(
  'cart-abandonment',
  '30 * * * *',
  $job$
    select net.http_get(
      url     := '__APP_URL__/api/cron/cart-abandonment',
      headers := jsonb_build_object('Authorization', 'Bearer __CRON_SECRET__')
    );
  $job$
);

-- Commerce: reconciliación de pagos MercadoPago (cada 30 min).
select cron.schedule(
  'payment-reconciliation',
  '*/30 * * * *',
  $job$
    select net.http_get(
      url     := '__APP_URL__/api/cron/payment-reconciliation',
      headers := jsonb_build_object('Authorization', 'Bearer __CRON_SECRET__')
    );
  $job$
);

-- Commerce: re-enganche de clientes inactivos (diario 14:00 UTC / 11:00 ART).
select cron.schedule(
  'reengagement',
  '0 14 * * *',
  $job$
    select net.http_get(
      url     := '__APP_URL__/api/cron/reengagement',
      headers := jsonb_build_object('Authorization', 'Bearer __CRON_SECRET__')
    );
  $job$
);

-- Commerce: reporte semanal de ROI al dueño (lunes 12:00 UTC / 09:00 ART).
select cron.schedule(
  'weekly-report',
  '0 12 * * 1',            -- Mondays at 12:00 UTC
  $job$
    select net.http_get(
      url     := '__APP_URL__/api/cron/weekly-report',
      headers := jsonb_build_object('Authorization', 'Bearer __CRON_SECRET__')
    );
  $job$
);

-- Commerce: pedido de reseñas de Google post-venta (cada hora a los :45).
select cron.schedule(
  'review-request',
  '45 * * * *',
  $job$
    select net.http_get(
      url     := '__APP_URL__/api/cron/review-request',
      headers := jsonb_build_object('Authorization', 'Bearer __CRON_SECRET__')
    );
  $job$
);

-- Campaigns: dispatch scheduled/sending campaigns in rate-limited batches (every minute).
select cron.schedule(
  'campaign-dispatch',
  '* * * * *',
  $job$
    select net.http_get(
      url     := '__APP_URL__/api/cron/campaign-dispatch',
      headers := jsonb_build_object('Authorization', 'Bearer __CRON_SECRET__')
    );
  $job$
);

-- Bookings: recordatorio de turnos ~24h antes (cada hora a los :10).
select cron.schedule(
  'appointment-reminders',
  '10 * * * *',
  $job$
    select net.http_get(
      url     := '__APP_URL__/api/cron/appointment-reminders',
      headers := jsonb_build_object('Authorization', 'Bearer __CRON_SECRET__')
    );
  $job$
);

-- Loyalty: saludo de cumpleaños con cupón (diario 13:00 UTC / 10:00 ART).
select cron.schedule(
  'birthday-greetings',
  '0 13 * * *',
  $job$
    select net.http_get(
      url     := '__APP_URL__/api/cron/birthday-greetings',
      headers := jsonb_build_object('Authorization', 'Bearer __CRON_SECRET__')
    );
  $job$
);

-- Monitoring (#6): health-check de integraciones + pipeline de IA (cada 10 min).
select cron.schedule(
  'health-check',
  '*/10 * * * *',
  $job$
    select net.http_get(
      url     := '__APP_URL__/api/cron/health-check',
      headers := jsonb_build_object('Authorization', 'Bearer __CRON_SECRET__')
    );
  $job$
);

-- Alertas de negocio (#5): stock bajo + caída de tasa de respuesta (cada hora a los :20).
select cron.schedule(
  'business-alerts',
  '20 * * * *',
  $job$
    select net.http_get(
      url     := '__APP_URL__/api/cron/business-alerts',
      headers := jsonb_build_object('Authorization', 'Bearer __CRON_SECRET__')
    );
  $job$
);

-- Reporte mensual (#5): resumen del mes al dueño (día 1 a las 12:00 UTC / 09:00 ART).
select cron.schedule(
  'monthly-report',
  '0 12 1 * *',
  $job$
    select net.http_get(
      url     := '__APP_URL__/api/cron/monthly-report',
      headers := jsonb_build_object('Authorization', 'Bearer __CRON_SECRET__')
    );
  $job$
);

-- Lead scoring: recalcula el puntaje de contactos activos (diario 05:00 UTC / 02:00 ART).
select cron.schedule(
  'lead-scoring',
  '0 5 * * *',
  $job$
    select net.http_get(
      url     := '__APP_URL__/api/cron/lead-scoring',
      headers := jsonb_build_object('Authorization', 'Bearer __CRON_SECRET__')
    );
  $job$
);

-- Follow-up de leads tibios (dentro de la ventana de 24h) (cada hora a los :35).
select cron.schedule(
  'lead-followup',
  '35 * * * *',
  $job$
    select net.http_get(
      url     := '__APP_URL__/api/cron/lead-followup',
      headers := jsonb_build_object('Authorization', 'Bearer __CRON_SECRET__')
    );
  $job$
);

-- NPS post-compra: envío de encuesta + recolección de respuestas (cada hora a los :50).
select cron.schedule(
  'nps',
  '50 * * * *',
  $job$
    select net.http_get(
      url     := '__APP_URL__/api/cron/nps',
      headers := jsonb_build_object('Authorization', 'Bearer __CRON_SECRET__')
    );
  $job$
);

-- Factura por WhatsApp: notifica al cliente su factura AFIP (cada 15 min).
select cron.schedule(
  'invoice-notify',
  '*/15 * * * *',
  $job$
    select net.http_get(
      url     := '__APP_URL__/api/cron/invoice-notify',
      headers := jsonb_build_object('Authorization', 'Bearer __CRON_SECRET__')
    );
  $job$
);

-- Waitlist: avisa cuando un producto sin stock vuelve a estar disponible (cada 30 min).
select cron.schedule(
  'waitlist-notify',
  '*/30 * * * *',
  $job$
    select net.http_get(
      url     := '__APP_URL__/api/cron/waitlist-notify',
      headers := jsonb_build_object('Authorization', 'Bearer __CRON_SECRET__')
    );
  $job$
);

-- Fidelidad: acumula puntos por órdenes pagas (cada hora a los :05).
select cron.schedule(
  'loyalty-accrual',
  '5 * * * *',
  $job$
    select net.http_get(
      url     := '__APP_URL__/api/cron/loyalty-accrual',
      headers := jsonb_build_object('Authorization', 'Bearer __CRON_SECRET__')
    );
  $job$
);

-- Pedidos recurrentes: recrea el pedido de siempre cuando corresponde (diario 11:00 UTC / 08:00 ART).
select cron.schedule(
  'recurring-orders',
  '0 11 * * *',
  $job$
    select net.http_get(
      url     := '__APP_URL__/api/cron/recurring-orders',
      headers := jsonb_build_object('Authorization', 'Bearer __CRON_SECRET__')
    );
  $job$
);

-- Verify they registered:
--   select jobname, schedule, active from cron.job
--   where jobname in ('buffer-flush', 'invoice-retry', 'tier-decay',
--     'cart-abandonment', 'payment-reconciliation', 'reengagement',
--     'weekly-report');
--
-- Inspect recent runs / failures:
--   select status, return_message, start_time
--   from cron.job_run_details
--   where jobid = (select jobid from cron.job where jobname = 'buffer-flush')
--   order by start_time desc limit 10;
--
-- Remove the job:
--   select cron.unschedule('buffer-flush');
